#!/bin/sh
# Copyright 2021 GlitchyByte
# SPDX-License-Identifier: Apache-2.0

# Gradle wrapper for GraalVM use.

# Setup GraalVM environment variables.
if test -n "$GRAALVM_HOME"; then
  export JAVA_HOME="$GRAALVM_HOME"
  GRAALVM_BIN="$GRAALVM_HOME/bin"
  export PATH="$GRAALVM_BIN:${PATH//$GRAALVM_BIN:/}"
else
  echo "No GraalVM found."
fi

# Source gradlew
. ./gradlew $*
